%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(gossiperl_types).

-include("gossiperl_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('digestEnvelope') ->
  {struct, [{1, string},
          {2, string},
          {3, string}]}
;

struct_info('digestForwardedAck') ->
  {struct, [{1, string},
          {2, string},
          {3, string}]}
;

struct_info('digestError') ->
  {struct, [{1, string},
          {2, i64},
          {3, i32},
          {4, string},
          {5, string},
          {6, string},
          {7, string}]}
;

struct_info('digestExit') ->
  {struct, [{1, string},
          {2, i64},
          {3, string}]}
;

struct_info('digestMember') ->
  {struct, [{1, string},
          {2, string},
          {3, i32},
          {4, i64}]}
;

struct_info('digestSubscription') ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, i64}]}
;

struct_info('digest') ->
  {struct, [{1, string},
          {2, i32},
          {3, i64},
          {4, string},
          {5, string}]}
;

struct_info('digestAck') ->
  {struct, [{1, string},
          {2, i64},
          {3, string},
          {4, {list, {struct, {'gossiperl_types', 'digestMember'}}}}]}
;

struct_info('digestSubscriptions') ->
  {struct, [{1, string},
          {2, i64},
          {3, string},
          {4, {list, {struct, {'gossiperl_types', 'digestSubscription'}}}}]}
;

struct_info('digestSubscribe') ->
  {struct, [{1, string},
          {2, i64},
          {3, string},
          {4, {list, string}},
          {5, string}]}
;

struct_info('digestUnsubscribe') ->
  {struct, [{1, string},
          {2, i64},
          {3, string},
          {4, {list, string}},
          {5, string}]}
;

struct_info('digestSubscribeAck') ->
  {struct, [{1, i64},
          {2, string},
          {3, {list, string}}]}
;

struct_info('digestUnsubscribeAck') ->
  {struct, [{1, i64},
          {2, string},
          {3, {list, string}}]}
;

struct_info('digestEvent') ->
  {struct, [{1, string},
          {2, string},
          {3, i64}]}
;

struct_info('digestForwardableTest') ->
  {struct, [{1, string}]}
;

struct_info('subscription') ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, i32},
          {5, i64}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('digestEnvelope') ->
  {struct, [{1, required, string, 'payload_type', undefined},
          {2, required, string, 'bin_payload', undefined},
          {3, required, string, 'id', undefined}]}
;

struct_info_ext('digestForwardedAck') ->
  {struct, [{1, required, string, 'name', undefined},
          {2, required, string, 'reply_id', undefined},
          {3, required, string, 'secret', undefined}]}
;

struct_info_ext('digestError') ->
  {struct, [{1, required, string, 'name', undefined},
          {2, required, i64, 'heartbeat', undefined},
          {3, required, i32, 'error_code', undefined},
          {4, required, string, 'error_entity', undefined},
          {5, required, string, 'error_entity_name', undefined},
          {6, required, string, 'error_message', undefined},
          {7, required, string, 'reply_id', undefined}]}
;

struct_info_ext('digestExit') ->
  {struct, [{1, required, string, 'name', undefined},
          {2, required, i64, 'heartbeat', undefined},
          {3, required, string, 'secret', undefined}]}
;

struct_info_ext('digestMember') ->
  {struct, [{1, required, string, 'member_name', undefined},
          {2, required, string, 'member_ip', undefined},
          {3, required, i32, 'member_port', undefined},
          {4, required, i64, 'member_heartbeat', undefined}]}
;

struct_info_ext('digestSubscription') ->
  {struct, [{1, required, string, 'event_type', undefined},
          {2, required, string, 'member_name', undefined},
          {3, required, string, 'origin', undefined},
          {4, required, i64, 'heartbeat', undefined}]}
;

struct_info_ext('digest') ->
  {struct, [{1, required, string, 'name', undefined},
          {2, required, i32, 'port', undefined},
          {3, required, i64, 'heartbeat', undefined},
          {4, required, string, 'id', undefined},
          {5, required, string, 'secret', undefined}]}
;

struct_info_ext('digestAck') ->
  {struct, [{1, required, string, 'name', undefined},
          {2, required, i64, 'heartbeat', undefined},
          {3, required, string, 'reply_id', undefined},
          {4, required, {list, {struct, {'gossiperl_types', 'digestMember'}}}, 'membership', []}]}
;

struct_info_ext('digestSubscriptions') ->
  {struct, [{1, required, string, 'name', undefined},
          {2, required, i64, 'heartbeat', undefined},
          {3, required, string, 'reply_id', undefined},
          {4, required, {list, {struct, {'gossiperl_types', 'digestSubscription'}}}, 'subscriptions', []}]}
;

struct_info_ext('digestSubscribe') ->
  {struct, [{1, required, string, 'name', undefined},
          {2, required, i64, 'heartbeat', undefined},
          {3, required, string, 'id', undefined},
          {4, required, {list, string}, 'event_types', []},
          {5, required, string, 'secret', undefined}]}
;

struct_info_ext('digestUnsubscribe') ->
  {struct, [{1, required, string, 'name', undefined},
          {2, required, i64, 'heartbeat', undefined},
          {3, required, string, 'id', undefined},
          {4, required, {list, string}, 'event_types', []},
          {5, required, string, 'secret', undefined}]}
;

struct_info_ext('digestSubscribeAck') ->
  {struct, [{1, required, i64, 'heartbeat', undefined},
          {2, required, string, 'reply_id', undefined},
          {3, required, {list, string}, 'event_types', []}]}
;

struct_info_ext('digestUnsubscribeAck') ->
  {struct, [{1, required, i64, 'heartbeat', undefined},
          {2, required, string, 'reply_id', undefined},
          {3, required, {list, string}, 'event_types', []}]}
;

struct_info_ext('digestEvent') ->
  {struct, [{1, required, string, 'event_type', undefined},
          {2, required, string, 'event_object', undefined},
          {3, required, i64, 'heartbeat', undefined}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

